### ISSUE TITLE
cannot run JS

### ISSUE THREAD

**Issue by no-mercy-here** [bots-business/help#15]
Hi there!
I'm trying to test JS and I've tried several commands, but for some reason they don't work. So I've taken one of the examples - Bot.sendMessage(2+2), and unfortunately, it doesn't work either. I keep getting an error - Oh. Error happened 😢. What can be the issue? Thank you in advance!
PS - I love Bots.Business so far, really hope to see JS working

**Comment by no-mercy-here** [comment]
Ok, I created another bot, tested the same command and it worked. Then I went back to the initial bot, tried the same command and it also works now. Not sure what it was, but it seems to work now. Hopefully, it will stay this way. Thank you guys for the awesome app!

**Comment by bots-business** [comment]
Thank you!
